// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7w2O8iDB4c-91aDNnuSnFA2FXYzcqrA',
    appId: '1:361185904079:android:a5a2109459e1af7bf87eba',
    messagingSenderId: '361185904079',
    projectId: 'stayinme-1af7d',
    storageBucket: 'stayinme-1af7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAew3HM8GUkYazA9_Vb2wmvqCCVwKj9i8Q',
    appId: '1:361185904079:ios:0f287109bc31e47cf87eba',
    messagingSenderId: '361185904079',
    projectId: 'stayinme-1af7d',
    storageBucket: 'stayinme-1af7d.firebasestorage.app',
    androidClientId: '361185904079-j9vvnk0t7q0tp2mh45lj2sa848qh13ik.apps.googleusercontent.com',
    iosClientId: '361185904079-fbsoi489m6573crs3mua0935kdi4c66s.apps.googleusercontent.com',
    iosBundleId: 'com.example.stayInMe.RunnerTests',
  );

}